document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'zh-CN\'>");
document.writeln("<head>");
document.writeln("    <meta charset=\'utf-8\'>");
document.writeln("    <meta http-equiv=\'X-UA-Compatible\' content=\'IE=edge\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1\'>");
document.writeln("    <meta name=\'description\' content=\'JVM学习笔记\'>");
document.writeln("    <meta name=\'author\' content=\'Avisen\'>");
document.writeln("    <link rel=\'icon\' href=\'../../favicon.ico\'>");
document.writeln("");
document.writeln("    <title>JVM学习笔记</title>");
document.writeln("");
document.writeln("    <style>");
document.writeln("        body {");
document.writeln("            padding-top: 50px;");
document.writeln("            padding-bottom: 20px;");
document.writeln("        }");
document.writeln("    </style>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("<div class=\'col-sm-3 col-sm-offset-1 blog-sidebar\'>");
document.writeln("    <h2>Blogs</h2><br>");
document.writeln("    <div class=\'sidebar-module\'>");
document.writeln("        <h4>JVM</h4>");
document.writeln("        <ol class=\'list-unstyled\'>");
document.writeln("            <li><a href=\'../javanote/JVMBlog01.html\'>JVM内存结构</a></li>");
document.writeln("            <li><a href=\'../javanote/JVMBlog02.html\'>JVM垃圾回收</a></li>");
document.writeln("            <li><a href=\'../javanote/JVMBlog03.html\'>JVM类加载</a></li>");
document.writeln("            <li><a href=\'../javanote/JVMBlog04.html\'>GC调优</a></li>");
document.writeln("            <li><hr></li>");
document.writeln("        </ol>");
document.writeln("    </div>");
document.writeln("    <div class=\'sidebar-module\'>");
document.writeln("        <h4>并发编程</h4>");
document.writeln("        <ol class=\'list-unstyled\'>");
document.writeln("            <li><a href=\'../javanote/threadBlog01.html\'>原子操作CAS</a></li>");
document.writeln("            <li><a href=\'../javanote/threadBlog02.html\'>显示锁和AQS</a></li>");
document.writeln("            <li><a href=\'../javanote/threadBlog03.html\'>线程池</a></li>");
document.writeln("            <li><a href=\'../javanote/threadBlog04.html\'>并发安全</a></li>");
document.writeln("            <li><hr></li>");
document.writeln("        </ol>");
document.writeln("    </div>");
document.writeln("    <div class=\'sidebar-module\'>");
document.writeln("        <h4>About me</h4>");
document.writeln("        <ol class=\'list-unstyled\'>");
document.writeln("            <li><a href=\'#\'>GitHub</a></li>");
document.writeln("            <li><a href=\'#\'>Twitter</a></li>");
document.writeln("        </ol>");
document.writeln("    </div>");
document.writeln("</div><!-- /.blog-sidebar -->");
document.writeln("</body>");
document.writeln("</html>");