document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'en\'>");
document.writeln("<head>");
document.writeln("    <meta charset=\'utf-8\'>");
document.writeln("    <meta http-equiv=\'X-UA-Compatible\' content=\'IE=edge\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1\'>");
document.writeln("    <meta name=\'description\' content=\'Avisen\'s study note\'>");
document.writeln("    <meta name=\'author\' content=\'Avisen\'>");
document.writeln("    <link rel=\'icon\' href=\'/avisen.github.com/assets/img/favicon.ico\'>");
document.writeln("");
document.writeln("    <title>小白的学习笔记</title>");
document.writeln("");
document.writeln("    <!-- Bootstrap core CSS -->");
document.writeln("    <link href=\'https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css\' rel=\'stylesheet\'>");
document.writeln("");
document.writeln("    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->");
document.writeln("    <link href=\'/avisen.github.com/assets/css/ie10-viewport-bug-workaround.css\' rel=\'stylesheet\'>");
document.writeln("");
document.writeln("    <!-- Just for debugging purposes. Don\'t actually copy these 2 lines! -->");
document.writeln("    <script src=\'/avisen.github.com/assets/js/ie-emulation-modes-warning.js\'></script>");
document.writeln("");
document.writeln("    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->");
document.writeln("    <!--[if lt IE 9]>");
document.writeln("    <script src=\'https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js\'></script>");
document.writeln("    <script src=\'https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js\'></script>");
document.writeln("    <![endif]-->");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("<nav class=\'navbar navbar-inverse navbar-fixed-top\'>");
document.writeln("    <div class=\'container\'>");
document.writeln("        <div class=\'navbar-header\'>");
document.writeln("            <button type=\'button\' class=\'navbar-toggle collapsed\' data-toggle=\'collapse\' data-target=\'#navbar\'");
document.writeln("                    aria-expanded=\'false\' aria-controls=\'navbar\'>");
document.writeln("                <span class=\'sr-only\'>Toggle navigation</span>");
document.writeln("                <span class=\'icon-bar\'></span>");
document.writeln("                <span class=\'icon-bar\'></span>");
document.writeln("                <span class=\'icon-bar\'></span>");
document.writeln("            </button>");
document.writeln("            <a class=\'navbar-brand\' href=\'../../index.html\'>Avisen\'s notebook</a>");
document.writeln("        </div><!--/.navbar-header -->");
document.writeln("");
document.writeln("        <div id=\'navbar\' class=\'navbar-collapse collapse\'>");
document.writeln("            <ul class=\'nav navbar-nav\'>");
document.writeln("                <li><a href=\'../../index.html\'><span class=\'glyphicon glyphicon-home\'></span> Home</a></li>");
document.writeln("                <li>");
document.writeln("                    <a href=\'#\' class=\'dropdown-toggle\' data-toggle=\'dropdown\'>");
document.writeln("                        <span class=\'glyphicon glyphicon-book\'></span> Notes");
document.writeln("                        <b class=\'caret\'></b>");
document.writeln("                    </a>");
document.writeln("                    <ul class=\'dropdown-menu\'>");
document.writeln("                        <li><a href=\'../javanote/jvmBlog01.html\'>JVM</a></li>");
document.writeln("                        <li><a href=\'../javanote/threadBlog01.html\'>并发编程</a></li>");
document.writeln("                        <li class=\'divider\'></li>");
document.writeln("                        <li><a href=\'#\'>设计模式</a></li>");
document.writeln("                        <li><a href=\'#\'>数据结构与算法</a></li>");
document.writeln("                        <li><a href=\'#\'>Linux</a></li>");
document.writeln("                        <li class=\'divider\'></li>");
document.writeln("                        <li><a href=\'#\'>MySQL调优</a></li>");
document.writeln("                    </ul>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                    <a href=\'#\' class=\'dropdown-toggle\' data-toggle=\'dropdown\'>");
document.writeln("                        <span class=\'glyphicon glyphicon-bookmark\'></span> 源码笔记");
document.writeln("                        <b class=\'caret\'></b>");
document.writeln("                    </a>");
document.writeln("                    <ul class=\'dropdown-menu\'>");
document.writeln("                        <li><a href=\'#\'>MyBatis源码系列</a></li>");
document.writeln("                        <li class=\'divider\'></li>");
document.writeln("                        <li><a href=\'#\'>Spring源码系列</a></li>");
document.writeln("                    </ul>");
document.writeln("                </li>");
document.writeln("                <li><a href=\'#\'><span class=\'glyphicon glyphicon-edit\'></span> 手写框架</a></li>");
document.writeln("            </ul>");
document.writeln("        </div><!--/.navbar-collapse -->");
document.writeln("    </div>");
document.writeln("</nav>");
document.writeln("<!-- Bootstrap core JavaScript");
document.writeln("================================================== -->");
document.writeln("<!-- Placed at the end of the document so the pages load faster -->");
document.writeln("<script src=\'https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js\'></script>");
document.writeln("<script src=\'https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js\'></script>");
document.writeln("<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->");
document.writeln("<script src=\'/assets/js/ie10-viewport-bug-workaround.js\'></script>");
document.writeln("</body>");
document.writeln("</html>");